IgleTableCommunication:
  urlIgleTabeControl: http://192.168.1.100:5000/nails_table/start_test_board_with_rtk
  urlStatusFromIgleTabe: http://192.168.1.100:5003/get_test_results

opc:
  url: opc.tcp://172.21.10.39:48010
  # url: opc.tcp://192.168.1.3:48010

modbus:
url: 192.168.1.100
port: 502

database:
  engine: postgresql
  host: localhost
  port: 5432
  user: myuser
  password: mypass
  name: mydatabase

logging:
  level: INFO
  file: logs/app.log